DEBUG 2021-04-20 19:35:34.777 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-20 19:35:34.778 UTC: 	 Running on: Linux lxplus758.cern.ch 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-20 19:35:34.778 UTC: 	 Executing command: 'submit'
DEBUG 2021-04-20 19:35:34.778 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
INFO 2021-04-20 19:35:34.779 UTC: 	 Will use CRAB configuration file crabConfig_Data_102x_analysis.py
DEBUG 2021-04-20 19:35:34.779 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-04-20 19:35:34.787 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-04-20 19:35:34.788 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016F' already exists 
Please change the requestName in the config file
ERROR 2021-04-20 19:35:34.788 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/ClientUtilities.py", line 402, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016F' already exists 
Please change the requestName in the config file
INFO 2021-04-20 19:35:34.793 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 06:01:05.475 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:01:05.476 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:01:05.476 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 06:01:05.476 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 06:01:05.503 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016B is not a valid CRAB project directory.
ERROR 2021-04-21 06:01:05.503 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016B is not a valid CRAB project directory.
INFO 2021-04-21 06:01:05.519 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 06:01:05.859 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:01:05.859 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:01:05.859 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 06:01:05.859 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 06:01:05.860 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016B is not a valid CRAB project directory.
ERROR 2021-04-21 06:01:05.860 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016B is not a valid CRAB project directory.
INFO 2021-04-21 06:01:05.862 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 06:01:30.923 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:01:30.923 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:01:30.923 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 06:01:30.923 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 06:01:30.924 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 06:01:30.925 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 06:01:30.926 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 06:06:59.599 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:06:59.599 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:06:59.599 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:06:59.599 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2021-04-21 06:06:59.929 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:06:59.929 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:06:59.929 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:06:59.929 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2021-04-21 06:07:00.282 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:07:00.283 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:07:00.283 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:07:00.283 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2021-04-21 06:07:00.612 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:07:00.612 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:07:00.612 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:07:00.612 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2021-04-21 06:07:00.945 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:07:00.946 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:07:00.946 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:07:00.946 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2021-04-21 06:07:01.280 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:07:01.281 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:07:01.281 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:07:01.281 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2021-04-21 06:07:01.670 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:07:01.670 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:07:01.670 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:07:01.670 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2021-04-21 06:07:02.038 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:07:02.038 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:07:02.038 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:07:02.039 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2021-04-21 06:27:08.960 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:27:08.961 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:27:08.961 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 06:27:08.961 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 06:27:08.963 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 06:27:08.963 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 06:27:08.969 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 06:50:47.470 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 06:50:47.470 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 06:50:47.470 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 06:50:47.470 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 06:50:47.471 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 06:50:47.472 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 06:50:47.476 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 07:13:22.066 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 07:13:22.066 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 07:13:22.066 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 07:13:22.066 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 07:13:22.711 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 07:13:22.711 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 07:13:25.735 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 07:38:40.445 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 07:38:40.445 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 07:38:40.445 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 07:38:40.446 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 07:38:40.446 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 07:38:40.447 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 07:38:41.675 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 12:38:42.122 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 12:38:42.122 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 12:38:42.122 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 12:38:42.122 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 12:38:42.123 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 12:38:42.123 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 12:38:42.170 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 16:41:35.184 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 16:41:35.184 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 16:41:35.184 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 16:41:35.185 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 16:41:35.186 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 16:41:35.186 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 16:41:35.279 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 16:42:52.265 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 16:42:52.266 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 16:42:52.266 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 16:42:52.266 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 16:42:52.268 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 16:42:52.268 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 16:42:52.271 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 17:20:15.323 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 17:20:15.323 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 17:20:15.323 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 17:20:15.323 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 17:20:15.340 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 17:20:15.340 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 17:20:15.382 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 18:05:58.479 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 18:05:58.480 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 18:05:58.480 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 18:05:58.480 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 18:05:58.481 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 18:05:58.481 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 18:05:58.537 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 19:19:19.433 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 19:19:19.434 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 19:19:19.434 UTC: 	 Executing command: 'status'
DEBUG 2021-04-21 19:19:19.434 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 19:19:19.435 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 19:19:19.435 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 19:19:19.473 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-04-21 19:21:33.081 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-21 19:21:33.082 UTC: 	 Running on: Linux lxplus727.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-04-21 19:21:33.082 UTC: 	 Executing command: 'resubmit'
DEBUG 2021-04-21 19:21:33.082 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2021-04-21 19:21:33.083 UTC: 	 Error: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
ERROR 2021-04-21 19:21:33.083 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/resubmit.py", line 26, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H is not a valid CRAB project directory.
INFO 2021-04-21 19:21:33.085 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_12/src/Test/QCDEventShape/test/crab.log
DEBUG 2021-05-14 07:05:38.241 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-05-14 07:05:38.241 UTC: 	 Running on: Linux lxplus776.cern.ch 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-05-14 07:05:38.241 UTC: 	 Executing command: 'submit'
DEBUG 2021-05-14 07:05:38.241 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
INFO 2021-05-14 07:05:38.242 UTC: 	 Will use CRAB configuration file crabConfig_Data_102x_analysis_H.py
DEBUG 2021-05-14 07:05:38.242 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-05-14 07:05:38.248 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-05-14 07:05:38.248 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_20/src/Test/QCDEventShape/test/crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H' already exists 
Please change the requestName in the config file
ERROR 2021-05-14 07:05:38.248 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/ClientUtilities.py", line 402, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_20/src/Test/QCDEventShape/test/crab_projects/crab_Event_Shape_Charge_Data_analysis_Run2016H' already exists 
Please change the requestName in the config file
INFO 2021-05-14 07:05:38.253 UTC: 	 Log file is /afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW/Eventshape_variables/Data_TUnfoldBinning/2016_UL/CMSSW_10_6_20/src/Test/QCDEventShape/test/crab.log
