DEBUG 2020-02-20 20:47:37.234 UTC: 	 Running on: Linux lxplus788.cern.ch 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-02-20 20:47:37.248 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-02-20 20:47:37.248 UTC: 	 Executing command: 'submit'
DEBUG 2020-02-20 20:47:37.248 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-02-20 20:47:37.255 UTC: 	 Checking credentials
DEBUG 2020-02-20 20:47:37.255 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-02-20 20:47:37.255 UTC: 	 Getting proxy life time left
DEBUG 2020-02-20 20:47:37.861 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 42842

 error: 
 retcode : 0
DEBUG 2020-02-20 20:47:38.469 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 42841

 error: 
 retcode : 0
DEBUG 2020-02-20 20:47:38.470 UTC: 	 Proxy lifetime 42842 secs is different from voms extension lifetime 42841 secs for proxy: /tmp/x509up_u107261
DEBUG 2020-02-20 20:47:38.470 UTC: 	 Proxy valid for 11:54:01 hours
INFO 2020-02-20 20:47:38.470 UTC: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2020-02-20 20:47:38.470 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-02-20 20:47:40.576 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-02-20 20:47:40.576 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/CMSSW_10_2_18/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2' already exists 
Please change the requestName in the config file
ERROR 2020-02-20 20:47:40.576 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/CMSSW_10_2_18/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2' already exists 
Please change the requestName in the config file
DEBUG 2020-02-22 06:31:02.985 UTC: 	 Running on: Linux lxplus702.cern.ch 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-02-22 06:31:03.004 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-02-22 06:31:03.004 UTC: 	 Executing command: 'status'
DEBUG 2020-02-22 06:31:03.005 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2020-02-22 06:31:03.024 UTC: 	 Error: crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2 is not a valid CRAB project directory.
ERROR 2020-02-22 06:31:03.024 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2 is not a valid CRAB project directory.
DEBUG 2020-02-23 19:03:15.786 UTC: 	 Running on: Linux lxplus715.cern.ch 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-02-23 19:03:15.802 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-02-23 19:03:15.802 UTC: 	 Executing command: 'submit'
DEBUG 2020-02-23 19:03:15.802 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-02-23 19:03:15.809 UTC: 	 Checking credentials
DEBUG 2020-02-23 19:03:15.810 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-02-23 19:03:15.810 UTC: 	 Getting proxy life time left
DEBUG 2020-02-23 19:03:16.414 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43166

 error: 
 retcode : 0
DEBUG 2020-02-23 19:03:17.019 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43166

 error: 
 retcode : 0
DEBUG 2020-02-23 19:03:17.019 UTC: 	 Proxy valid for 11:59:26 hours
INFO 2020-02-23 19:03:17.020 UTC: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2020-02-23 19:03:17.020 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-02-23 19:03:19.254 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-02-23 19:03:19.255 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/CMSSW_10_2_18/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2' already exists 
Please change the requestName in the config file
ERROR 2020-02-23 19:03:19.255 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/CMSSW_10_2_18/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2' already exists 
Please change the requestName in the config file
DEBUG 2020-02-25 21:02:21.145 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-02-25 21:02:21.181 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-02-25 21:02:21.182 UTC: 	 Executing command: 'submit'
DEBUG 2020-02-25 21:02:21.184 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-02-25 21:02:21.227 UTC: 	 Checking credentials
DEBUG 2020-02-25 21:02:21.227 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-02-25 21:02:21.227 UTC: 	 Getting proxy life time left
DEBUG 2020-02-25 21:02:22.344 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43133

 error: 
 retcode : 0
DEBUG 2020-02-25 21:02:23.258 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43132

 error: 
 retcode : 0
DEBUG 2020-02-25 21:02:23.258 UTC: 	 Proxy lifetime 43133 secs is different from voms extension lifetime 43132 secs for proxy: /tmp/x509up_u107261
DEBUG 2020-02-25 21:02:23.258 UTC: 	 Proxy valid for 11:58:52 hours
INFO 2020-02-25 21:02:23.258 UTC: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2020-02-25 21:02:23.259 UTC: 	 Loading CRAB configuration file.
ERROR 2020-02-25 21:02:23.280 UTC: 	 Error while loading CRAB configuration:
invalid syntax (crab_flat_pythia8.py, line 34)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-02-25 21:02:23.281 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
invalid syntax (crab_flat_pythia8.py, line 34)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-02-25 21:04:24.352 UTC: 	 Running on: Linux lxplus740.cern.ch 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-02-25 21:04:24.373 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-02-25 21:04:24.373 UTC: 	 Executing command: 'submit'
DEBUG 2020-02-25 21:04:24.374 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-02-25 21:04:24.388 UTC: 	 Checking credentials
DEBUG 2020-02-25 21:04:24.388 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-02-25 21:04:24.388 UTC: 	 Getting proxy life time left
DEBUG 2020-02-25 21:04:25.196 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43010

 error: 
 retcode : 0
DEBUG 2020-02-25 21:04:26.003 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43010

 error: 
 retcode : 0
DEBUG 2020-02-25 21:04:26.003 UTC: 	 Proxy valid for 11:56:50 hours
INFO 2020-02-25 21:04:26.003 UTC: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2020-02-25 21:04:26.004 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-02-25 21:04:28.634 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-02-25 21:04:28.635 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/CMSSW_10_2_18/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2' already exists 
Please change the requestName in the config file
ERROR 2020-02-25 21:04:28.635 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/CMSSW_10_2_18/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2' already exists 
Please change the requestName in the config file
DEBUG 2020-03-01 09:03:27.490 UTC: 	 Running on: Linux lxplus714.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-01 09:03:27.506 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-03-01 09:03:27.507 UTC: 	 Executing command: 'status'
DEBUG 2020-03-01 09:03:27.507 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2020-03-01 09:03:27.509 UTC: 	 Error: crab_projects/crab_ESV_Trigger_Run_v2_JetHT_Run2017F-31Mar2018-v1/ is not a valid CRAB project directory.
ERROR 2020-03-01 09:03:27.509 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_ESV_Trigger_Run_v2_JetHT_Run2017F-31Mar2018-v1/ is not a valid CRAB project directory.
DEBUG 2020-03-02 06:58:29.641 UTC: 	 Running on: Linux lxplus760.cern.ch 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-02 06:58:29.659 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-03-02 06:58:29.660 UTC: 	 Executing command: 'status'
DEBUG 2020-03-02 06:58:29.660 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-03-07 19:04:13.992 UTC: 	 Running on: Linux lxplus700.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-07 19:04:14.007 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-03-07 19:04:14.008 UTC: 	 Executing command: 'status'
DEBUG 2020-03-07 19:04:14.008 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
ERROR 2020-03-07 19:04:14.039 UTC: 	 Error: crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_7Mar20/ is not a valid CRAB project directory.
ERROR 2020-03-07 19:04:14.039 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_7Mar20/ is not a valid CRAB project directory.
DEBUG 2020-03-17 06:59:11.069 UTC: 	 Running on: Linux lxplus783.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-17 06:59:11.094 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-03-17 06:59:11.094 UTC: 	 Executing command: 'submit'
DEBUG 2020-03-17 06:59:11.096 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-03-17 06:59:11.106 UTC: 	 Checking credentials
DEBUG 2020-03-17 06:59:11.107 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-03-17 06:59:11.107 UTC: 	 Getting proxy life time left
DEBUG 2020-03-17 06:59:11.813 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43176

 error: 
 retcode : 0
DEBUG 2020-03-17 06:59:12.418 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43175

 error: 
 retcode : 0
DEBUG 2020-03-17 06:59:12.419 UTC: 	 Proxy lifetime 43176 secs is different from voms extension lifetime 43175 secs for proxy: /tmp/x509up_u107261
DEBUG 2020-03-17 06:59:12.419 UTC: 	 Proxy valid for 11:59:35 hours
INFO 2020-03-17 06:59:12.419 UTC: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2020-03-17 06:59:12.419 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-03-17 06:59:14.862 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-03-17 06:59:14.864 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/MC_Fall17MiniAODv2-PU2017_12Apr2018/CMSSW_10_6_2/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_17Mar20_PU_HLT' already exists 
Please change the requestName in the config file
ERROR 2020-03-17 06:59:14.864 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/MC_Fall17MiniAODv2-PU2017_12Apr2018/CMSSW_10_6_2/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_17Mar20_PU_HLT' already exists 
Please change the requestName in the config file
DEBUG 2020-03-19 09:28:49.148 UTC: 	 Running on: Linux lxplus756.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-19 09:28:49.205 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-03-19 09:28:49.206 UTC: 	 Executing command: 'submit'
DEBUG 2020-03-19 09:28:49.207 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-03-19 09:28:49.244 UTC: 	 Checking credentials
DEBUG 2020-03-19 09:28:49.244 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-03-19 09:28:49.244 UTC: 	 Getting proxy life time left
DEBUG 2020-03-19 09:28:49.848 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 43152

 error: 
 retcode : 0
DEBUG 2020-03-19 09:28:50.454 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 43151

 error: 
 retcode : 0
DEBUG 2020-03-19 09:28:50.455 UTC: 	 Proxy lifetime 43152 secs is different from voms extension lifetime 43151 secs for proxy: /tmp/x509up_u107261
DEBUG 2020-03-19 09:28:50.455 UTC: 	 Proxy valid for 11:59:11 hours
INFO 2020-03-19 09:28:50.455 UTC: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2020-03-19 09:28:50.455 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-03-19 09:28:50.483 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-03-19 09:28:50.495 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/MC_Fall17MiniAODv2-PU2017_12Apr2018/CMSSW_10_6_2/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_17Mar20_PU_HLT_2' already exists 
Please change the requestName in the config file
ERROR 2020-03-19 09:28:50.495 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/MC_Fall17MiniAODv2-PU2017_12Apr2018/CMSSW_10_6_2/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_17Mar20_PU_HLT_2' already exists 
Please change the requestName in the config file
DEBUG 2020-03-22 21:09:53.280 UTC: 	 Running on: Linux lxplus712.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-22 21:09:53.337 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-03-22 21:09:53.338 UTC: 	 Executing command: 'submit'
DEBUG 2020-03-22 21:09:53.339 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-03-22 21:09:53.400 UTC: 	 Checking credentials
DEBUG 2020-03-22 21:09:53.401 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-03-22 21:09:53.401 UTC: 	 Getting proxy life time left
DEBUG 2020-03-22 21:09:54.005 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 42337

 error: 
 retcode : 0
DEBUG 2020-03-22 21:09:54.613 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 42336

 error: 
 retcode : 0
DEBUG 2020-03-22 21:09:54.613 UTC: 	 Proxy lifetime 42337 secs is different from voms extension lifetime 42336 secs for proxy: /tmp/x509up_u107261
DEBUG 2020-03-22 21:09:54.613 UTC: 	 Proxy valid for 11:45:36 hours
INFO 2020-03-22 21:09:54.613 UTC: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2020-03-22 21:09:54.613 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-03-22 21:09:54.646 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-03-22 21:09:54.682 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/MC_Fall17MiniAODv2-PU2017_12Apr2018/CMSSW_10_6_2/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_19Mar2020' already exists 
Please change the requestName in the config file
ERROR 2020-03-22 21:09:54.682 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/MC_Fall17MiniAODv2-PU2017_12Apr2018/CMSSW_10_6_2/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_19Mar2020' already exists 
Please change the requestName in the config file
DEBUG 2020-03-23 22:15:18.239 UTC: 	 Running on: Linux lxplus747.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-23 22:15:18.292 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-03-23 22:15:18.292 UTC: 	 Executing command: 'submit'
DEBUG 2020-03-23 22:15:18.295 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sukundu/.crab3
DEBUG 2020-03-23 22:15:18.327 UTC: 	 Checking credentials
DEBUG 2020-03-23 22:15:18.327 UTC: 	 Found proxy file /tmp/x509up_u107261
DEBUG 2020-03-23 22:15:18.327 UTC: 	 Getting proxy life time left
DEBUG 2020-03-23 22:15:19.032 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -timeleft
 output : 14667

 error: 
 retcode : 0
DEBUG 2020-03-23 22:15:19.637 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u107261 -actimeleft
 output : 14666

 error: 
 retcode : 0
DEBUG 2020-03-23 22:15:19.637 UTC: 	 Proxy lifetime 14667 secs is different from voms extension lifetime 14666 secs for proxy: /tmp/x509up_u107261
DEBUG 2020-03-23 22:15:19.637 UTC: 	 Proxy valid for 04:04:26 hours
INFO 2020-03-23 22:15:19.638 UTC: 	 Will use CRAB configuration file crab_flat_pythia8.py
DEBUG 2020-03-23 22:15:19.638 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-03-23 22:15:19.665 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-03-23 22:15:19.680 UTC: 	 Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/MC_Fall17MiniAODv2-PU2017_12Apr2018/CMSSW_10_6_2/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_23Mar2020' already exists 
Please change the requestName in the config file
ERROR 2020-03-23 22:15:19.680 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/sukundu/private/ESV_charge_CMSSW_10_2_18/PYTHIA8_flat/MC_Fall17MiniAODv2-PU2017_12Apr2018/CMSSW_10_6_2/src/Test/QCDEventShape/test/crab_projects/crab_ESVQCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8_2017_V2_23Mar2020' already exists 
Please change the requestName in the config file
